version: '3.8'

services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"  # Expose the React app on port 3000
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  playwright-tests:
    build:
      context: ./test-project
      dockerfile: Dockerfile.playwright
    depends_on:
      react-app:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - PLAYWRIGHT_BASE_URL=http://react-app:3000
    volumes:
      - ./allure-results:/tests/allure-results
  
  allure-generator:
    build: 
      context: ./allure-generator
      dockerfile: Dockerfile-allure
    depends_on:
      - playwright-tests
    volumes:
      - ./allure-results:/tests/allure-results  # Map host allure-results to container
      - ./allure-report:/tests/allure-report  # Output report on the host
    command: ["generate", "/tests/allure-results", "--clean", "-o", "/tests/allure-report"]
    networks:
      - app-network
  
  allure-server:
    image: nginx:alpine
    depends_on:
      - allure-generator
    volumes:
      - ./allure-report:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
