# Use the official Playwright image as the base
FROM mcr.microsoft.com/playwright:v1.46.0-jammy

WORKDIR /tests

# Copy the Playwright tests and configuration
COPY playwright-ui-test-framework/ .


# Install Allure Commandline and Java (OpenJDK 11)
RUN npm install -g allure-commandline --save-dev && \
    apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get clean


# Install specific browsers and devices
RUN npx playwright install chrome firefox webkit

# Set JAVA_HOME environment variable
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

# Expose the directory for Allure results
VOLUME /tests/allure-results

# Run Playwright tests
CMD ["/entrypoint.sh"]
